-- MySQL Workbench Synchronization
-- Generated: 2014-10-06 20:12
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Alejandro Romero

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

ALTER SCHEMA `test`  DEFAULT COLLATE utf8_general_ci ;

ALTER TABLE `test`.`message` 
COLLATE = utf8_general_ci ,
DROP COLUMN `message_text`,
ADD COLUMN `mesage_text` TEXT NULL DEFAULT NULL AFTER `id`,
ADD COLUMN `author_id` INT(11) NULL DEFAULT NULL AFTER `message_date`;

CREATE TABLE IF NOT EXISTS `test`.`author` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
